server {
    listen 4173;

    location /api/ {
        proxy_pass http://backend:8081/api/;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}