/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViolationsRouteImport } from './routes/violations'
import { Route as VehiculesRouteImport } from './routes/vehicules'
import { Route as UtilisateursRouteImport } from './routes/utilisateurs'
import { Route as RadarsRouteImport } from './routes/radars'
import { Route as MonVehiculeRouteImport } from './routes/mon-vehicule'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DetectionsRouteImport } from './routes/detections'
import { Route as IndexRouteImport } from './routes/index'

const ViolationsRoute = ViolationsRouteImport.update({
  id: '/violations',
  path: '/violations',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiculesRoute = VehiculesRouteImport.update({
  id: '/vehicules',
  path: '/vehicules',
  getParentRoute: () => rootRouteImport,
} as any)
const UtilisateursRoute = UtilisateursRouteImport.update({
  id: '/utilisateurs',
  path: '/utilisateurs',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarsRoute = RadarsRouteImport.update({
  id: '/radars',
  path: '/radars',
  getParentRoute: () => rootRouteImport,
} as any)
const MonVehiculeRoute = MonVehiculeRouteImport.update({
  id: '/mon-vehicule',
  path: '/mon-vehicule',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectionsRoute = DetectionsRouteImport.update({
  id: '/detections',
  path: '/detections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/login': typeof LoginRoute
  '/mon-vehicule': typeof MonVehiculeRoute
  '/radars': typeof RadarsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/vehicules': typeof VehiculesRoute
  '/violations': typeof ViolationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/login': typeof LoginRoute
  '/mon-vehicule': typeof MonVehiculeRoute
  '/radars': typeof RadarsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/vehicules': typeof VehiculesRoute
  '/violations': typeof ViolationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/detections': typeof DetectionsRoute
  '/login': typeof LoginRoute
  '/mon-vehicule': typeof MonVehiculeRoute
  '/radars': typeof RadarsRoute
  '/utilisateurs': typeof UtilisateursRoute
  '/vehicules': typeof VehiculesRoute
  '/violations': typeof ViolationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/detections'
    | '/login'
    | '/mon-vehicule'
    | '/radars'
    | '/utilisateurs'
    | '/vehicules'
    | '/violations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/detections'
    | '/login'
    | '/mon-vehicule'
    | '/radars'
    | '/utilisateurs'
    | '/vehicules'
    | '/violations'
  id:
    | '__root__'
    | '/'
    | '/detections'
    | '/login'
    | '/mon-vehicule'
    | '/radars'
    | '/utilisateurs'
    | '/vehicules'
    | '/violations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DetectionsRoute: typeof DetectionsRoute
  LoginRoute: typeof LoginRoute
  MonVehiculeRoute: typeof MonVehiculeRoute
  RadarsRoute: typeof RadarsRoute
  UtilisateursRoute: typeof UtilisateursRoute
  VehiculesRoute: typeof VehiculesRoute
  ViolationsRoute: typeof ViolationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/violations': {
      id: '/violations'
      path: '/violations'
      fullPath: '/violations'
      preLoaderRoute: typeof ViolationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicules': {
      id: '/vehicules'
      path: '/vehicules'
      fullPath: '/vehicules'
      preLoaderRoute: typeof VehiculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilisateurs': {
      id: '/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof UtilisateursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radars': {
      id: '/radars'
      path: '/radars'
      fullPath: '/radars'
      preLoaderRoute: typeof RadarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-vehicule': {
      id: '/mon-vehicule'
      path: '/mon-vehicule'
      fullPath: '/mon-vehicule'
      preLoaderRoute: typeof MonVehiculeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detections': {
      id: '/detections'
      path: '/detections'
      fullPath: '/detections'
      preLoaderRoute: typeof DetectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DetectionsRoute: DetectionsRoute,
  LoginRoute: LoginRoute,
  MonVehiculeRoute: MonVehiculeRoute,
  RadarsRoute: RadarsRoute,
  UtilisateursRoute: UtilisateursRoute,
  VehiculesRoute: VehiculesRoute,
  ViolationsRoute: ViolationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
